[project]
name = "blood-moon"
version = "3.0.0"
description = "A small script to control the lighting of the moon that has a philips hue lamp inside"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "phue>=1.1",
    "ephem>=4.1.6",
    "rich-click>=1.9.8",
    "python-dotenv>=1.0.1"
]


[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "pytest>=9.1.1",
    "pytest-freezer>=0.4.9",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "slotscheck>=0.20.1",
    "inline-snapshot>=0.35.4"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
build = "scripts.build:build"
blood_moon = "scripts.build:blood_moon"
help_svg = "scripts.build:help_svg"

[tool.coverage.report]
fail_under = 100

[tool.pytest.ini_options]
pythonpath = ["."]
norecursedirs = ["scripts"]

[tool.inline-snapshot]
format-command="ruff check --fix-only --stdin-filename {filename} | ruff format --stdin-filename {filename}"

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9", # pycodestyle errors
    "F",              # pyflakes
    "DTZ",            # naive datetimes
    "I",              # import sorting
    "UP",             # pyupgrade
    "B",              # bugbear
    "SIM",            # simplify
]
